### ISSUE TITLE
UI Testing sounds good

### ISSUE THREAD

**Issue by crisnieto** [testingarmeetup/propuestas#4]
### Esta es una propuesta para

* [x] Una charla
* [ ] Un workshop

**Nota: Por favor marcar uno solo**

### Abstract

Aplicar tests de UI escalables en el mundo de mobile nativo puede ser un camino más que tedioso. Con qué paredes nos vamos a chocar desde que hacemos el primer test de UI hasta tener una suite completa funcionando periódicamente es una pregunta qué pocas veces se hace; menos aún, cómo hacer que los tests sean viables en el tiempo. La idea de la charla es mostrar la estrategia que seguimos en MercadoLibre para poder automatizar tests de UI de manera escalable, concientizando por qué son costosos de mantener pero también por qué son necesarios en nuestro producto.

### Requerimientos

Speaker :)

### Personas que van a brindar el workshop/charla

Cristian Nieto

### Duracion

10 minutos alcanzan para mostrar toda la estrategia a nivel general :)

**Comment by rodrigojmartin** [comment]
Buenísimo, gracias!

**Comment by nachoesmite** [comment]
Buenisima la talk ;)
