### ISSUE TITLE
Chaos Engineering

### ISSUE THREAD

**Issue by rodrigojmartin** [testingarmeetup/propuestas#5]
### Esta es una propuesta para

* [x] Una charla
* [ ] Un workshop

**Nota: Por favor marcar uno solo**

### Abstract

Ultimamente me interesé mucho en el tema de Chaos Engineering, asi que qué mejor que dar una lightning talk para reforzar conceptos y compartir lo aprendido!

### Requerimientos

Nada!
### Personas que van a brindar el workshop/charla

Rodrigo Martín

### Duracion

5 minutos (Lightning Talk)

**Comment by nachoesmite** [comment]
Buenisima la charla :)
